Issue #14 - Added Viewer Tools to ToolsCatalog and Added About Page
oss-slu/rerum-playground pull request #19
Opened 2024-09-30 20:59 UTC by sesheppard

New About page added to the branch, populated with the provided information about JSON, JSON LD, and Manifests. Adno and Universal Viewer added to ToolsCatalog file with the existing entries. Styles still need to be separated from the HTML documents, and further work likely still needs to be done on the layout and content of the About page.

2024-09-30 23:57 UTC, haneenalsewari commented on web/about.html
> +            <!--This is not the correct way to prevent text from moving behind the page footer. I will need to figure out the issue and revise this shortly.-->
You can adjust the 'footer' CSS by increasing the bottom margin or applying a 'min-height' to the page to make sure that the content does not overlap

2024-10-01 00:15 UTC, haneenalsewari commented on web/about.html
> +            <h2>What is a JSON Manifest?</h2>
I agree with your comment! I think you need a more thorough explanation of JSON manifests, it's a little brief and doesn't have enough context for understanding.

2024-10-01 16:30 UTC, kate-holdener commented
> New About page added to the branch, populated with the provided information about JSON, JSON LD, and Manifests. Adno and Universal Viewer added to ToolsCatalog file with the existing entries. Styles still need to be separated from the HTML documents, and further work likely still needs to be done on the layout and content of the About page.

Please use
Fixes #14
In the PR description

2024-10-01 23:56 UTC, alar12 commented on web/about.html
> +
Use separate external CSS file and also we should be using same fonts and their sizes across the website.

2024-10-01 23:57 UTC, alar12 commented on web/about.html
> +            <p>https://iiif.io/api/cookbook/</p>
(https://iiif.io/api/cookbook/) links should be hyperlinked

2024-10-02 00:02 UTC, alar12 requested changes
Good Work!
Create new CSS file for styling and need more information on JSON Manifests like what they does and why they are created - visit: [IIIF Cookbook](https://iiif.io/api/cookbook/) and https://iiif.io/guides/using_iiif_resources/.

2024-10-10 02:07 UTC, alar12 approved these changes
Good Work!!, This works for the current sprint (need to modify CSS for footer)

2024-10-10 02:07 UTC, merged