Recently used tools
oss-slu/rerum-playground pull request #21
Opened 2024-09-30 21:04 UTC by haneenalsewari

Fixes #12
The "Recently Used" feature was added to the tools page. When a tool is clicked, it is moved to the top of the tools list. The first three tools in the list will display a "Recently Used" badge. This order and the recently used status will persist across page refreshes by storing the data as a JSON object in local storage.
The team needed a functionality that tracks user interactions with the tools and maintains an order for the most recently used tools. This enhances the user experience by providing quick access to frequently used tools.
The changes involved adding logic to track which tool was clicked, updating the tool order accordingly, and saving that order in localStorage. Tools are displayed in order of recency, and badges are added for the top three recently used tools. The tool list is re-rendered after every click to ensure the order is maintained. Finally, the state is persisted across page refreshes by utilizing the browser’s localStorage.
This feature is not currently complete, I am running into some issues and am still working on them.

2024-10-01 16:27 UTC, kate-holdener commented
@haneenalsewari I believe this PR was closed because develop branch is no longer used in this repo. Your PRs should go to the main branch. When you start working on a feature/fix, create a branch starting the latest code in main.

2024-10-01 23:37 UTC, alar12 commented on web/js/playground.js
> +    // console.log('tool index in toolscatalog:', toolIndex);
Clear the commented out code before pushing to your branch/ making a PR

2024-10-01 23:42 UTC, alar12 commented on web/js/playground.js
> +
You have almost implemented it but the functionality blocks opening the tool. Also only navPlace Object and T-PEN are getting the label on top. We need it for all the tools in tool page.

2024-10-01 23:45 UTC, alar12 requested changes
Good Work!
You have almost implemented it but the functionality blocks opening a tool. Also only navPlace Object and T-PEN are getting the label on top. We need it for all the tools in tool page. Also the tools list should automatically reorder after a tool is used, with the most recently used tool appearing first.

2024-10-08 16:15 UTC, alar12 approved these changes
Perfect!! The functionality is working as mentioned in the requirements.

2024-10-08 16:16 UTC, merged