implementing local storage for manifest links
oss-slu/rerum-playground pull request #31
Opened 2024-10-14 15:41 UTC by haneenalsewari

Fixes #15
The ability to store and retrieve manifest links using local storage has been implemented. Now, when a user inputs a manifest link, it persists across page reloads by saving it in the browser's local storage.
This change was necessary to ensure users don't lose their manifest links upon page refresh or closure, enhancing the usability of the tool by remembering past inputs
A new manifestStorage.js file was created to handle saving and retrieving manifest links from local storage. The UI was also updated in tools.html to allow users to input and save a manifest link. Upon page load, any saved manifest links will be retrieved and displayed.

2024-10-14 22:27 UTC, haydenkarl22 commented on web/js/manifestStorage.js
> +    // avoid duplicates, add new manifest link if not already present
I don't think this comment is necessary, id recommend removing it.

2024-10-14 22:28 UTC, haydenkarl22 commented on web/js/manifestStorage.js
> + * Retrieve the stored manifest links from local storage
this comment is also not necessary, id also remove this one.

2024-10-15 19:14 UTC, alar12 requested changes
I see the functionality is implemented well but need to link with @haydenkarl22 #17. As it is merged in main go ahead and pull the changes from main and link the functionality. Also render the url's in local storage below the url box.

2024-10-16 04:30 UTC, alar12 approved these changes
The functionality is working well as per requirement good work!!.

2024-10-16 04:30 UTC, merged