Issue #35 - Consolidate JS
oss-slu/rerum-playground pull request #39
Opened 2024-10-28 20:59 UTC by sesheppard

Fixing Issue #35

2024-10-29 03:57 UTC, haydenkarl22 commented on web/js/playground.js
> +/**
pretty minor thing but if you could change this comment styling to // id greatly appreciate it.

2024-10-29 03:57 UTC, haydenkarl22 commented on web/tools.html
>  </html>
So far so good, the comments are very informative as to what your code is doing. Great work!

2024-10-29 16:19 UTC, alar12 requested changes
The JavaScript needs to be separated from the HTML and placed into a dedicated JS file. This separation has caused malfunctions, specifically with the menu bar and the tools page. Please ensure that all functionalities work as intended after separating, and verify that the codebase operates seamlessly, maintaining the same functionality as before.

2024-11-07 08:36 UTC, alar12 approved these changes
Internal JS is moved to the external files as intended.

Need to separate tools.html JS from playground.js further!!!

2024-11-07 08:36 UTC, merged