Partially implemented sorting behavior for tools
oss-slu/rerum-playground pull request #46
Opened 2024-11-11 21:35 UTC by haneenalsewari

Issue #44 

**What Was Done:**
- Implemented functionality for updating the recently used tools by moving the clicked tool to the top.

- Badges are correctly applied to the top three recently used tools.

**What Remains Unresolved:**
- Sorting behavior still has issues with tool order after multiple clicks. The clicked tool moves to the top, but other tools are not consistently shifting as expected.

- The solution needs further refinement to ensure all tools shift one position to the right upon clicking a new tool.

**Next Steps:**
- Investigate and refine the logic to manage the tool order consistently.

- Test the badge application to ensure it remains on only the top three recently used tools.

2024-11-12 05:32 UTC, sesheppard commented on web/js/playground.js
> +    saveRecentlyUsedTools(recentTools.slice(0, 3));
I suppose this is a way to keep track of the top tools, if it works as expected.

2024-11-12 05:32 UTC, sesheppard commented on web/js/playground.js
> +        !recentTools.some(recentTool => recentTool.label === tool.label))];
I can only find where the list of recent tools is passed between functions within the code, and not where it is initially defined. What exactly moves a tool to the top of the list when it is used?

2024-11-12 23:25 UTC, alar12 requested changes
Ensure that when a tool is used it moves to the top and the previous tool moves to the second position, and so on.

2024-11-19 17:42 UTC, alar12 commented
The tools are not displayed on the page when the local storage is empty.

2024-11-30 20:26 UTC, alar12 approved these changes

2024-11-30 20:26 UTC, merged